services:
  - type: web
    name: django-app
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn setup.wsgi:application
    preDeployCommand: "python manage.py migrate && python manage.py shell < create_superuser.py"
    staticPublishPath: staticfiles
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: setup.settings
      - key: PYTHON_VERSION
        value: 3.11
