services:
  - type: web
    name: django-app
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn setup.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: setup.settings
      - key: PYTHON_VERSION
        value: 3.11
