# Generated by Django 5.2.1 on 2025-05-22 02:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="O número de telefone deve estar no formato: '+999999999'. Até 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='OperationDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('type_operation', models.BooleanField(choices=[(True, 'Entrada'), (False, 'Saída')], default=True, verbose_name='Tipo de operação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=15, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('sell_without_stock', models.BooleanField(default=False, verbose_name='Vender sem estoque')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='Unity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Unidade')),
                ('abbreviation', models.CharField(max_length=4, verbose_name='Abreviação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='OutProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('operation_date', models.DateTimeField(blank=True, null=True, verbose_name='Data da operação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saidas', to='controlstock.customer', verbose_name='Cliente')),
                ('operation_description', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saidas', to='controlstock.operationdescription', verbose_name='Tipo de operação')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saidas', to='controlstock.product', verbose_name='Produto')),
            ],
        ),
        migrations.CreateModel(
            name='EntryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('operation_description', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='controlstock.operationdescription', verbose_name='Tipo de operação')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='controlstock.product', verbose_name='Produto')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='unity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='controlstock.unity', verbose_name='Unidade'),
        ),
    ]
